export const colombiaData = {
  Amazonas: ["Leticia", "Puerto Nariño"],
  Antioquia: [
    "Medellín",
    "Envigado",
    "Itagüí",
    "Bello",
    "Rionegro",
    "Apartadó",
    "Turbo",
    "Caucasia",
  ],
  Arauca: ["Arauca", "Arauquita", "Saravena", "Tame", "Fortul"],
  Atlántico: [
    "Barranquilla",
    "Soledad",
    "Malambo",
    "Baranoa",
    "Galapa",
    "Sabanalarga",
  ],
  Bolívar: [
    "Cartagena",
    "Magangué",
    "Turbaco",
    "Arjona",
    "El Carmen de Bolívar",
    "Mompós",
  ],
  Boyacá: [
    "Tunja",
    "Duitama",
    "Sogamoso",
    "Chiquinquirá",
    "Samacá",
    "Paipa",
    "Villa de Leyva",
  ],
  Caldas: [
    "Manizales",
    "Villamaría",
    "Chinchiná",
    "Riosucio",
    "La Dorada",
    "Salamina",
  ],
  Caquetá: [
    "Florencia",
    "Morelia",
    "Puerto Rico",
    "San Vicente del Caguán",
    "Belén de los Andaquíes",
  ],
  Casanare: ["Yopal", "Aguazul", "Villanueva", "Maní", "Monterrey"],
  Cauca: [
    "Popayán",
    "Santander de Quilichao",
    "Cajibío",
    "Totoró",
    "Puerto Tejada",
  ],
  Cesar: [
    "Valledupar",
    "Aguachica",
    "Bosconia",
    "Curumaní",
    "La Jagua de Ibirico",
  ],
  Chocó: ["Quibdó", "Istmina", "Condoto", "Tadó", "Riosucio"],
  Córdoba: ["Montería", "Cereté", "Sahagún", "Lorica", "Montelíbano"],
  Cundinamarca: [
    "Bogotá",
    "Soacha",
    "Chía",
    "Zipaquirá",
    "Fusagasugá",
    "Girardot",
    "Facatativá",
  ],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare"],
  Huila: ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Manaure", "Fonseca"],
  Magdalena: ["Santa Marta", "Ciénaga", "Fundación", "El Banco", "Aracataca"],
  Meta: ["Villavicencio", "Acacías", "Granada", "San Martín", "Puerto López"],
  Nariño: ["Pasto", "Ipiales", "Tumaco", "Túquerres", "La Unión"],
  "Norte de Santander": [
    "Cúcuta",
    "Ocaña",
    "Pamplona",
    "Villa del Rosario",
    "Los Patios",
  ],
  Putumayo: ["Mocoa", "Puerto Asís", "Orito", "La Hormiga", "Sibundoy"],
  Quindío: ["Armenia", "Calarcá", "Montenegro", "Quimbaya", "Salento"],
  Risaralda: [
    "Pereira",
    "Dosquebradas",
    "Santa Rosa de Cabal",
    "La Virginia",
    "Marsella",
  ],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  Santander: [
    "Bucaramanga",
    "Floridablanca",
    "Girón",
    "Piedecuesta",
    "Barrancabermeja",
  ],
  Sucre: ["Sincelejo", "Corozal", "Sampués", "Tolú", "San Marcos"],
  Tolima: ["Ibagué", "Espinal", "Melgar", "Lérida", "Honda"],
  "Valle del Cauca": [
    "Cali",
    "Palmira",
    "Buenaventura",
    "Tuluá",
    "Buga",
    "Cartago",
    "Jamundí",
  ],
  Vaupés: ["Mitú"],
  Vichada: ["Puerto Carreño"],
};
